//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
        }
        [Display(Name ="Mã đơn đặt hàng")]
        public string MaDonDatHang { get; set; }
        [Display(Name ="Ngày lập đơn")]
        public Nullable<System.DateTime> NgayLap { get; set; }
        [Display(Name ="Tổng tiền")]
        public Nullable<int> TongThanhTien { get; set; }
        public Nullable<int> MaTinhTrang { get; set; }
        public string UserID { get; set; }
        [Display(Name ="Ghi chú")]
        public string GhiChu { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
