//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.HinhAnhs = new HashSet<HinhAnh>();
        }

        public int MaSanPham { get; set; }
        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "Cần nhập tên sản phẩm")]
        public string TenSanPham { get; set; }

        // xem chỗ này
        [Display(Name = "Giá nhập vào")] // add using System.ComponentModel.DataAnnotations;
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Cần nhập số nguyên")]
        [Required(ErrorMessage = "Cần nhập số nguyên")]
        public Nullable<int> GiaSanPham { get; set; }
        //

        [Display(Name = "Ngày nhập")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayNhap { get; set; }
        [Display(Name = "Sô lượng")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "Cần nhập số nguyên")]
        [Required(ErrorMessage = "Cần nhập số nguyên")]
        public Nullable<int> SoLuongTon { get; set; }
        [Display(Name = "Số lượng đã bán")]
        public Nullable<int> SoLuongBan { get; set; }
        [Display(Name = "Số lược xem")]
        public Nullable<int> SoLuocXem { get; set; }
        [Display(Name = "Mô tả")]
        public string MoTa { get; set; }
        public Nullable<int> BiXoa { get; set; }
        [Display(Name = "Loại sản phẩm")]
        public Nullable<int> MaLoaiSanPham { get; set; }
        [Display(Name = "Hãng sản xuất")]
        public Nullable<int> MaHangSanXuat { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
